config/routes.rb
Rails.application.routes.draw do
  resources :tokens do
    member do
      patch 'toggle_used'
    end
  end
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "guest_login", to: "guest_login#new"
  post "guest_login", to: "guest_login#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  resources :songs do
    put :upvote, on: :member
    put :downvote, on: :member
    put :played, on: :member
    delete :remove_all, on: :collection	
  end
  delete '/leave_jam', to: 'guest_login#destroy', as: :leave_jam
  root "home#index"
  resources :songs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/token.rb
class Token < ApplicationRecord

    belongs_to :user

end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: %i[ show edit update destroy ]

  # GET /tokens or /tokens.json
  def index
    @tokens = Token.all
    @token = Token.new
  end

  # GET /tokens/1 or /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens or /tokens.json
  def create
    @token = Token.new(
      code: generate_unique_code,
      used: false,
      user_id: Current.user.id,
      email: Current.user.email
    )

    respond_to do |format|
      if @token.save
        format.html { redirect_to tokens_path, notice: "Token was successfully created." }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1 or /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to token_url(@token), notice: "Token was successfully updated." }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1 or /tokens/1.json
  def destroy
    @token.destroy!

    respond_to do |format|
      format.html { redirect_to tokens_url, notice: "Token was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_used
    @token = Token.find(params[:id])
    @token.update(used: !@token.used)

    puts "\n\nChanged: " + @token.used.to_s + "\n\n"

    respond_to do |format|
      format.js # Add this line if you want to handle the response with JavaScript (optional)
      format.html { redirect_to tokens_path, notice: 'Token used status toggled successfully.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def token_params
      params.require(:token).permit(:code)
    end

    def generate_unique_code
      loop do
        code = generate_random_code
        return code unless Token.exists?(code: code)
      end
    end

    def generate_random_code
      # Generate a random 6-character code
      SecureRandom.hex(3)
    end
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/views/tokens/_form.html.erb
<%= form_with(model: token) do |form| %>
  <% if token.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
        <% token.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.button type: :submit, class: "icon-button" do %>
      <i class="fa-solid fa-circle-plus" class="add-token-button"></i>
    <% end %>
  </div>

<% end %>

app/views/tokens/_token.html.erb
<%= form_for token, url: toggle_used_token_path(token), method: :patch, remote: true do |f| %>
  <button type="submit" class="token-card">
    <% if token.used %>
      <div class="used-token"><%= token.code %> (used)</div>
    <% else %>
      <%= token.code %>
    <% end %>
  </button>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing token</h1>

<%= render "form", token: @token %>

<br>

<div>
  <%= link_to "Show this token", @token %> |
  <%= link_to "Back to tokens", tokens_path %>
</div>

app/views/tokens/index.html.erb
<!-- <p style="color: green; margin: 3em;"><%= notice %></p> -->

<div style="margin: 3em;">
  <%= link_to root_path, class: "home-button"  do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
</div>

<div class="token-header">
  <h1>Tokens</h1>
  <%= render "form", token: @token %>
</div>
<div id="tokens">
  <% @tokens.each do |token| %>
    <% if Current.user.email == token.email%>
      <div class="card_with_button">
        <%= render token %>
        <div class="fill"></div>
        <button class="copy-button" data-copy-text="<%= token.code %>">
          <i class="fa-solid fa-copy"></i>
        </button>
        <div class="upvote_button">
          <%= button_to token_path(token), method: :delete, remote: true, style: "background: none; border: none; padding: 0; cursor: pointer;" do %>
            <i class="fa-solid fa-trash" style="font-size: 1.5em; color: #d74d3e; padding: 1.14em;"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>


<p style="margin: 6em; font-size: .5em;">&#169 2023, Zero Budget Solutions. All rights reserved.</p>

app/views/tokens/new.html.erb
<div style="margin: 3em;">
  <%= link_to tokens_path, class: "home-button"  do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
</div>

<div class="light-heading">
  <h1>New token</h1>
</div>

<%= render "form", token: @token %>

app/views/tokens/show.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<%= render @token %>

<div>
  <%= link_to "Edit this token", edit_token_path(@token) %> |
  <%= link_to "Back to tokens", tokens_path %>

  <%= button_to "Destroy this token", @token, method: :delete %>
</div>