config/routes.rb
Rails.application.routes.draw do
  resources :tokens do
    member do
      patch 'toggle_used'
    end
  end
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "guest_login", to: "guest_login#new"
  post "guest_login", to: "guest_login#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  resources :songs do
    put :upvote, on: :member
    put :downvote, on: :member
    put :played, on: :member
    delete :remove_all, on: :collection	
  end
  delete '/leave_jam', to: 'guest_login#destroy', as: :leave_jam
  root "home#index"
  resources :songs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/views/home/index.html.erb
<!-- <div class="notice"><%= notice %></div> -->

<div class="user-info">
  <p><%= Current.user.email %></p>
  <i class="fa-solid fa-circle-user"></i>
</div>

<h2 class="home_title">Your current jam</h2>
<div class="section-link" onclick="window.location='<%= songs_path %>'">
  <i class="fa-solid fa-compact-disc icon-padding"></i>
  <%= link_to "Enter jam", songs_path, class: "text-decor-setting" %>
</div>

<div id="start-delete-button" class="section-link">
  <div id="delete-on" style="display: block;">
    <i class="fa-solid fa-trash icon-padding"></i>
    <%= link_to "Remove all played songs", '#', class: "text-decor-setting" %>
  </div>
  <div id="delete-off" style="display: none;">
    <i class="fa-solid fa-ban icon-padding"></i>
    <%= link_to "Cancel", '#', class: "text-decor-setting" %>
  </div>
</div>

<%= link_to remove_all_songs_path, method: :delete, style: "color: white; width: 100%; height: 100%;" do %>
  <div id="remove-all-songs" class="section-link section-delete-link" style="display: none;">
    <i class="fa-solid fa-triangle-exclamation icon-padding"></i> Remove all played songs
  </div>
<% end %>

<h2 class="home_title">Available tokens</h2>
<div class="section-link" onclick="window.location='<%= tokens_path %>'">
  <i class="fa-solid fa-user-gear icon-padding"></i>
  <%= link_to "All tokens", tokens_path, class: "text-decor-setting" %>
</div>
<!-- <div>
  <%= link_to "Create more tokens (todo)", new_token_path, class: "section-link" %>
</div> -->

<h2 class="home_title">Account settings</h2>
<div class="section-link" onclick="window.location='<%= edit_password_path %>'">
  <i class="fa-solid fa-key icon-padding"></i>
  <%= link_to "Change password", edit_password_path, class: "text-decor-setting" %>
</div>
<div class="section-link" onclick="window.location='<%= edit_identity_email_path %>'">
  <i class="fa-solid fa-envelope icon-padding"></i>
  <%= link_to "Change email address", edit_identity_email_path, class: "text-decor-setting" %>
</div>
<div class="section-link" onclick="window.location='<%= sessions_path %>'">
  <i class="fa-solid fa-desktop icon-padding"></i>
  <%= link_to "Devices & Sessions", sessions_path, class: "text-decor-setting" %>
</div>
<%= button_to "Log out", Current.session, method: :delete, class: "section-link log-out-button"%>

<p class="rights-comment">&#169 2023, Zero Budget Solutions. All rights reserved.</p>