config/routes.rb
Rails.application.routes.draw do
  resources :tokens do
    member do
      patch 'toggle_used'
    end
  end
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  get "guest_login", to: "guest_login#new"
  post "guest_login", to: "guest_login#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource  :password, only: [:edit, :update]
  namespace :identity do
    resource :email,              only: [:edit, :update]
    resource :email_verification, only: [:show, :create]
    resource :password_reset,     only: [:new, :edit, :create, :update]
  end
  resources :songs do
    put :upvote, on: :member
    put :downvote, on: :member
    put :played, on: :member
    delete :remove_all, on: :collection	
  end
  delete '/leave_jam', to: 'guest_login#destroy', as: :leave_jam
  root "home#index"
  resources :songs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/song.rb
class Song < ApplicationRecord
    validates_presence_of :title, :artist
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  skip_before_action :authenticate
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.order(upvotes: :desc)
  end

  # GET /songs/1 or /songs/1.json
  def show
    if params[:id] == "remove_all"
      remove_all
      return
    end
    @song = Song.find(params[:id])
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)
    @song.upvotes = 0
    t = Token.find_by(code: session[:current_token])
    @song.dj = t.email


    if Song.where('lower(title) = ? AND lower(artist) = ? AND dj = ?', @song.title.downcase, @song.artist.downcase, t.email).exists?
      redirect_to new_song_path, alert: "Song already played or is in the queue..."
      return
    end

    respond_to do |format|
      if @song.save
        format.html { redirect_to songs_path, notice: "Song was successfully added..." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_all
    current_user_email = session[:current_user_email]
    songs_to_be_deleted = Song.where(dj: current_user_email, played: true)
    songs_to_be_deleted.delete_all

    respond_to do |format|
      format.html { redirect_to root_path, notice: 'All played songs were successfully removed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @song = Song.find(params[:id])
    @song.increment!(:upvotes)

    Upvote.create(song_id: @song.id, token_code: session[:current_token])

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def downvote
    @song = Song.find(params[:id])
    @song.decrement!(:upvotes)

    Upvote.find_by(song_id: @song.id, token_code: session[:current_token]).destroy

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  def played
    @song = Song.find(params[:id])
    @song.update(played: true)
    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      if params[:id] == "remove_all"
        remove_all
        return
      end
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :upvotes, :played)
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :title, placeholder: "Title", class: "general-input" %>
  </div>
  <div>
    <%= form.text_field :artist, placeholder: "Artist", class: "general-input" %>
  </div>
  <p class="invalid-code"><%= alert %></p>

  <div class="button-margin">
    <%= form.button type: :submit, class: "general-submit-button" do %>
      <i class="fa-solid fa-floppy-disk"></i>
    <% end %>
  </div>

<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>" class="song_card">
  <p style="font-size: 1.2em; margin: 0; font-weight: bold;">
    <%= song.title %>
  </p>

  <p style="font-size: .8em;">
    Artist:
    <%= song.artist %>
  </p>

  <p style="font-size: .8em; margin: 0;">
    <%= pluralize(song.upvotes, 'upvote') %>
  </p>


</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<!-- <p id="notice" style="color: green; margin: 1em 3em;"><%= notice %></p> -->

<% if session[:current_user_email] %>
  <div style="margin: 3em;">
    <%= link_to root_path, class: "home-button"  do %>
      <i class="fa-solid fa-house"></i>
    <% end %>
  </div>
<% end %>

<% if session[:current_token] %>
  <div class="buttons-footer">
    <%= button_to leave_jam_path, method: :delete, title: "Leave jam", class: "button-styling button-styling-logout" do %>
      <i class="fa-solid fa-power-off"></i>
    <% end %>

    <%= link_to new_song_path do %>
      <i class="fa-solid fa-plus button-styling"></i>
    <% end %>
  </div>
<% end %>

<div class="light-heading">
  <h1 style="margin: 1.5em 0;">Top Songs:</h1>
</div>

<div id="songs">
  <% @songs.each do |song| %>
    <% if !song.played %>
      <% matching_user = User.find_by(email: session[:current_user_email]) %>
      
      <% if matching_user %>
        <% if song.dj == matching_user.email %>

          <div class="card_with_button">
            <%= render song %>
            <div class="upvote_button">
              <%= button_to played_song_path(song), method: :put, remote: true, style: "background: none; border: none; padding: 0; cursor: pointer;" do %>
                <i class="fa-regular fa-circle-check" style="font-size: 1.5em; color: #9E4784; padding: 2em;"></i>
              <% end %>
            </div>  
          </div>
          
        <% end %>
      <% else %>

        <% if session[:current_token] %>
          <% matching_token = Token.find_by(code: session[:current_token]) %>
          <% if matching_token && matching_token.email == song.dj %>

            <div class="card_with_button">
              <%= render song %>

              <% if !Upvote.find_by(song_id: song.id, token_code: session[:current_token]) %>

                <div class="upvote_button">
                  <%= button_to upvote_song_path(song), method: :put, remote: true, style: "background: none; border: none; padding: 0; cursor: pointer;" do %>
                    <i class="fa-solid fa-angle-up" style="font-size: 1.5em; color: #7bdc98; padding: 2.2em;"></i>
                  <% end %>
                </div>

              <% else %>

              <div class="upvote_button">
                <%= button_to downvote_song_path(song), method: :put, remote: true, style: "background: none; border: none; padding: 0; cursor: pointer;" do %>
                  <i class="fa-solid fa-angle-down" style="font-size: 1.5em; color: #d74d3e; padding: 2.2em;"></i>
                <% end %>
              </div>  

              <% end %>

            </div>

          <% end %>
        <% end %>  
      <% end %>  

    <% end %>   
  <% end %>
</div>

<p style="margin: 6em; font-size: .5em;">&#169 2023, Zero Budget Solutions. All rights reserved.</p>

app/views/songs/new.html.erb
<div style="margin: 3em;">
  <%= link_to songs_path, class: "home-button"  do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
</div>

<div class="light-heading">
  <h1>New song</h1>
</div>

<%= render "form", song: @song %>

<p class="rights-comment">&#169 2023, Zero Budget Solutions. All rights reserved.</p>

app/views/songs/show.html.erb
<!-- <p style="color: green"><%= notice %></p> -->

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>